framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []



    #     App\Entity\User:
    # properties:
    #     name:
    #          Length:
    #             min: 2
    #             max: 5
    #             minMessage: 'Your first name must be at least {{ limit }} characters long'
    #             maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
